#!/bin/bash
if [ $# -eq 0 ]; then
	file=$(yad --title "Select file to extract" --width 500 --height 400 --file --button="gtk-ok:0")
else
	file="$1"
fi
folder=$(yad --title "Select folder to extract to" --width 500 --height 400 --file --directory --button="gtk-ok:0")
ext=$(echo $file | sed 's/.*\.//')
case $ext in
	zip) unzip "$file" -d "$folder";;
	[gz,bz2]) tar xvf "$file" -C "$folder";;
	rar) unrar x "$file" "$folder";;
esac
