#!/bin/bash
function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" https://imgu$
}

imagepath=$(scrot -d 2 '%m-%d-%I:%M:%S_$wx$h.png' -e 'mv $f ~/images/ && echo "$
uploadImage "$imagepath" | xclip -selection clipboard
notify-send "$(echo $imagepath | cut -d/ -f 5) uploaded"
