#!/bin/bash
function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" https://imgur.com/api/upload.xml | grep -E -o "<original_image>(.)*</original_image>" | grep -E -o "http://i.imgur.com/[^<]*"
}

if [[ $# == 0 ]]
then
	imagepath=$(scrot '%m-%d-%I:%M:%S_$wx$h.png' -e 'mv $f ~/Pictures/ && mogrify -interlace PNG '/home/parker/Pictures/\$f' && echo "/home/parker/Pictures/$f"')
	uploadImage "$imagepath" | xclip -selection clipboard
	notify-send "$(echo $imagepath | cut -d/ -f 5) uploaded"
else
	uploadImage "$1" | xclip -selection clipboard
	notify-send "$(echo "$1") uploaded"
fi
